name: sport_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1
  sqflite_common_ffi: ^2.1.1+1
  sqflite: ^2.0.2+1
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  google_fonts: ^3.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  freezed: ^2.0.3+1


flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/migration/init.sql
    - assets/migration/sportsmen_test.sql

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
